### ISSUE TITLE
Outliner not working for me - possible fix?

### ISSUE THREAD

**Issue by macguffin** [bfanger/pixi-inspector#102]
Hi thanks for this tool, have been using it for years and it's almost impossible to imagine building PixiJS stuff without it!!

Not sure how my set up differs from yours but I get this error when using the outliner.

VM17162:351 Uncaught TypeError: Cannot use 'in' operator to search for 'getBoundingClientRect' in undefined
    at calibrateOverlay (<anonymous>:351:37)
    at updateHighlight (<anonymous>:378:9)

Had a look at your code and it seems that changing (pixiDevToolsVierport.ts line 56)

```
 if (devtools.app) {
        return devtools.app.view;
      }
```

to 

```
 if (devtools.app) {
        return devtools.app.renderer.view;
      }
```

in pixiDevToolsVierport.ts works for my stuff and your demo files

Not sure if I have permission to do a pull request and as it's such a minor fix just posting it here.

Thanks :)
Matt

**Comment by bfanger** [comment]
Thanks!
Should be fixed in the next version.
