### ISSUE TITLE
inspector fails to load pixi when it's running in an iFrame

### ISSUE THREAD

**Issue by tombolabrad** [bfanger/pixi-inspector#105]
the previous version of the inspector had no problem finding pixi when the application was running inside an iframe, now it is getting cors issues when trying to connect

**Comment by bfanger** [comment]
The older (soon deprecated) chrome extension api was more powerful.

Not sure if this can be fixed.

**Comment by biased-badger** [comment]
My app is not running in iframe, however I get CORS error too:

```
DOMException: Blocked a frame with origin "http://localhost:3000" from accessing a cross-origin frame. at getGlobal (<anonymous>:11:28) at Object.root (<anonymous>:20:23) at Object.tree (<anonymous>:309:31) at <anonymous>:1:27
```
