### ISSUE TITLE
Upload to firefox extensions

### ISSUE THREAD

**Issue by miltoncandelero** [bfanger/pixi-inspector#106]
It just works!
(There is maybe some extra changes needed like setting some correct urls, but it works!)

![image](https://user-images.githubusercontent.com/15253010/224049915-35c3b256-804f-4265-80e5-9ba0f302b998.png)

You can check the crx file in the firefox extension test for extra diagnostics
https://www.extensiontest.com/

**Comment by bfanger** [comment]
Excellent! I did write 2.0.0 with alternative browsers in mind but was expecting that more work would be needed.

**Comment by bfanger** [comment]
Download from https://addons.mozilla.org/en-US/firefox/addon/pixijs-devtools/

(when the submission is reviewed)
