### ISSUE TITLE
0.5.0 floods console with PIXI warnings

### ISSUE THREAD

**Issue by cltatman** [bfanger/pixi-inspector#11]
My project is using pixi 3.0.11, no warnings appear if I disable the extension 

![image](https://cloud.githubusercontent.com/assets/6932310/15094871/6ee38476-1466-11e6-9f0d-8727c1fb7e69.png)

**Comment by bfanger** [comment]
To prevent these deprecation warnings the inspector switches detection bases on version, but i didn't add a switch for `__VERSION__` any idea why it doesn't report 3.0.11?

**Comment by cltatman** [comment]
@bfanger no, looking into that now

**Comment by cltatman** [comment]
@bfanger looks like the `__VERSION__` problem is related to pixijs/pixi.js@5a53e383, my webpack-based pipeline wasn't respecting the new browserify transform requirement

i've always had the issue with `__VERSION__`, but the previous version of pixi-inspector didn't emit any warnings. i'm not sure why that would be

**Comment by thesunlover** [comment]
Hello, @bfanger 
thanks for nice plugin :+1: 
I have similar issue with the last version (4.0.0): in there the Warning is:
pixi.js:23356 Deprecation Warning: AstractFilter has been renamed to Filter, please use PIXI.Filter
