### ISSUE TITLE
Objects Set To Invisible Block Right Click For Objects Underneath

### ISSUE THREAD

**Issue by ColtonPhillips** [bfanger/pixi-inspector#113]
In the previous version of the pixi-inspector, one could turn foreground elements invisible in order to position those underneath of it, however turning a layer as invisible does not allow the user to subsequently click through to the underlying layer, to select it and change it's positioning. 

This forces the user to have to manually dig through the tree structure to find the object, which is less intuitive and more difficult.

![image](https://user-images.githubusercontent.com/1751509/226044535-c1cc869e-1ce1-44b9-9d8b-336cabc67dec.png)

**Comment by bfanger** [comment]
In the ray function from https://github.com/bfanger/pixi-inspector/blob/main/packages/pixi-panel/src/pixi-devtools/pixiDevtoolsViewport.ts the invisible nodes should be ignored

Blender/Figma also has a not-selectable toggle, that could also be a useful feature for the devtool.
