### ISSUE TITLE
Property Window is Empty when selecting node while using custom renderer

### ISSUE THREAD

**Issue by phaze-ZA** [bfanger/pixi-inspector#117]
Steps:
Create a pixi project using your own renderer and stage
Specify root node manually with: 
`globalThis.__PIXI_STAGE__ = yourContainer;` 
And add renderer with: 
`globalThis.__PIXI_RENDERER__ = yourRenderer;` 
Open devtools and go to the pixijs tab
Select a node
See property window stays empty, node still gets output to console though

Created a playground here for you to test on: https://www.pixiplayground.com/#/edit/0VzcIuYJ9eqQJoY-RrEvM  

Tried this using the PIXI.Application method, and it works perfectly fine - so I think it's specific to the above method.

**Comment by phaze-ZA** [comment]
To add to this, it seems to only be introduced with 2.6.0. I have teammates on 2.5.0 who do not have this problem.

**Comment by bfanger** [comment]
Fixed in 2.6.1, Thanks for reporting!

**Comment by phaze-ZA** [comment]
Thank you for the quick turnaround!
