### ISSUE TITLE
missing props

### ISSUE THREAD

**Issue by djmisterjon** [bfanger/pixi-inspector#121]
they was available and very useful in old version, not sure why they are removed in the new design !?

**interactivity**
- interactive
- buttonMode
- interactiveChildren

![image](https://github.com/bfanger/pixi-inspector/assets/24865815/8ee356cc-a749-472a-a9e8-1b22a336c207)

**Comment by bfanger** [comment]
The old version exposed **all** properties and guessed the type as a flat list. This resulted a cluttered list where some props worked and others didn't. The list also contained deprecated props which resulted lots of console errors in the past.

The new setup uses deliberate grouped editors for known properties.
 I can look into adding an "interactivity panel", are other properties aside from the 3 you've mentioned that would be useful in this panel?

**Comment by djmisterjon** [comment]
thanks friend you awesome 😄
