### ISSUE TITLE
Adjusting Pixi Textfield Position

### ISSUE THREAD

**Issue by jeth88** [bfanger/pixi-inspector#122]
Hi,

I find this plugin tool very useful and I am really thankful (to you) for creating this one.

I would like to request for the improvement like having the ability to adjust the textfield position (x and y) so it would easy for us rearrange its position in the canvas.

I hope to hear from you soon.

Cheers!

**Comment by jethsas** [comment]
I decided to put it inside a container and that's where I can modify the x and y position in real-time.

**Comment by jeth88** [comment]
I decided to put it inside a container and that's where I can modify the x and y position in real-time.

**Comment by bfanger** [comment]
Could you provide more information about which textfield didn't have the ability to change position?

I couldn't reproduce the issue, for `PIXI.Text` the position is editable, but you need to switch from the "Text Properties" tab (Blue "a") to the "Object Properties" tab (orange square)
