### ISSUE TITLE
Pixi.js with Vue 3 debug issue

### ISSUE THREAD

**Issue by ramkrishnakuldeep** [bfanger/pixi-inspector#125]
Hello, 
I am currently using `vue3-pixi` with Vue 3.
I want to know how to setup pixi-inspector with vue 3
I tried below code 
```
import { useStage, useApplication, useRenderer } from 'vue3-pixi'
onMounted(() => {
     (globalThis as any).__PIXI_STAGE__ = useStage();
    (globalThis as any).__PIXI_RENDERER__ = useRenderer();
})
```
but couldn't see the inspector the pixi app.

![image](https://github.com/bfanger/pixi-inspector/assets/30339561/1933881f-26c0-470a-b571-d6f47bbc2ccd)

Any help would be appreciated

**Comment by bfanger** [comment]
You're assigning a vue ref to `__PIXI_STAGE__`, not a PIXI.Container object., to get the  value use `useStage().value` 

PS. the PIXI.Application exposes the both the stage and renderer so:

```vue
<script setup>
import { watchEffect } from 'vue';
import { useApplication } from 'vue3-pixi';

const app = useApplication();
watchEffect(() => {
  globalThis.__PIXI_APP__ = app.value;
});
</script>
```

Should be enough
