### ISSUE TITLE
Add "log to console" feature

### ISSUE THREAD

**Issue by martinnikolov93** [bfanger/pixi-inspector#126]
In previous versions of the plugin it was possible to log specific element to the console. Which was very useful for debugging.

Is it possible to add such feature to the new version?

**Comment by martinnikolov93** [comment]
Just found the variable $pixi is the currently selected node. I'm closing the issue.

**Comment by bfanger** [comment]
Tip: Double-clicking in the treeview will also log the node

**Comment by martinnikolov93** [comment]
Thank you, it's very helpful!
