### ISSUE TITLE
pixijs v4 compatibility

### ISSUE THREAD

**Issue by macguffin** [bfanger/pixi-inspector#13]
Hi just tried your excellent tool with the new version of pixijs. It works but no longer shows the transform properties as I'm guessing pixijs have changed the way they store these.
Do you still use this tool yourself?
Are you still developing it?

I will have a look at pixi.inspector.js and see if it's something I can fix.
Thanks 
Matt

**Comment by csomakk** [comment]
At my company we haven't yet moved to Pixi4 due to some bugs, so I didn't try the inspector yet. Feel free to fix it, but please maintain functionality for older version as well ;)

**Comment by macguffin** [comment]
No I haven't switched yet and one of the things stopping me was this not working as I can't use pixijs without it ;)

Never experimented with chrome extensions so I'll see what I can do.

**Comment by csomakk** [comment]
its not that difficult, pretty much JS with an API.
one trick to have the inspector window detached (separate window) then with
the key combo you can open an inspector for the inspector to debug :D

if you get stuck, ping me, and I'll help and update readme :)


On Friday, September 9, 2016, macguffin <notifications@github.com> wrote:
> No I haven't switched yet and one of the things stopping me was this not
working as I can't use pixijs without it ;)
>
> Never experimented with chrome extensions so I'll see what I can do.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/N2UBDAaw-A_NZWj5T1N_O_ypSq4OgjZObZapF6PIREWFWyHwo83YH4TpQiFohfwEXA-6yAC6U8OU2LY5Fmboo7wQR4eCZOaJDJQ3ZOusfUZzZPL0E4bHXXLXhEdrmpeYiFj6uQTFEBodOHVSfLUZPbyJnGmn3A=s0-d-e1-ft#https://github.com/notifications/beacon/AAma1sd_9UNlnaNGuJHvBQbsWhqkQALAks5qoUIDgaJpZM4J463E.gif>

**Comment by bfanger** [comment]
0.7.0 Adds support for the position, rotation, scale & skew properties in pixijs v4's transform property.
Let me know if its causing any issues.

**Comment by macguffin** [comment]
Wow that was quick!!
Works as expected thanks for that.

FYI your package.json has gulp-util missing. So I couldn't build until I'd manually installed it.

Thanks again.
Matt

**Comment by csomakk** [comment]
nice and swift ;)
