### ISSUE TITLE
Publish 0.8.0

### ISSUE THREAD

**Issue by JulioC** [bfanger/pixi-inspector#17]
Please, publish the new version on Chrome Web Store. I couldn't download it from the link in README nor searching for it on the store.

**Comment by csomakk** [comment]
https://chrome.google.com/webstore/detail/pixi-inspector/aamddddknhcagpehecnhphigffljadon?hl=en works perfectly for me. what issue did you get?

**Comment by JulioC** [comment]
For me, the displayed version is 0.7.0:

![image](https://user-images.githubusercontent.com/387794/30812087-460240a2-a1e0-11e7-8bb5-4f6b08dc0ca6.png)

**Comment by csomakk** [comment]
Yeah, click "Add to chrome"

**Comment by csomakk** [comment]
according to https://github.com/bfanger/pixi-inspector/releases  0.7.0 is the latest, what exactly are you expecting with a 0.8.0?

**Comment by JulioC** [comment]
Didn't realize that! I believe support for `__PIXI_INSPECTOR_GLOBAL_HOOK__` was added after that.

**Comment by csomakk** [comment]
yeah, thats true
meanwhile you can expose your PIXI variable from your iframe :)
i do it like

> PIXI = iframe.contentWindow.PIXI

**Comment by bfanger** [comment]
0.8 hasn’t been released yet, i’ve rewritten a lot of code and would like to do some additional testing. 

Testing and feedback would be great, to run 0.8 follow the “build from source” instructions in the readme

**Comment by JulioC** [comment]
Thanks! We've been using it without issues.

**Comment by bfanger** [comment]
I’ve released 0.8.0 🎉

**Comment by csomakk** [comment]
NICE JOB, CONGRATS :)
