### ISSUE TITLE
Getting events from the inspector where inspector has been injected

### ISSUE THREAD

**Issue by hendrysadrak** [bfanger/pixi-inspector#19]
Could there be support for listening for events like element clicked in the TreeView from the page where inspector has been injected?

**Comment by bfanger** [comment]
It could, but why?
What is the use-case?

**Comment by hendrysadrak** [comment]
The project i'm working on has been optimized to not render when nothing has changed, only renders when there is an user input or animation etc. But without rendering pixi-inspector doesn't get the data. 

Currently i'm listening to `window.onMessage` and checking when `INSPECTOR` event has been sent  so that when pressing reconnect button in devtools the tree will be updated but features like highlighting or changing values realtime don't work. 

Perfect would be if the added event would also contain reference to DisplayObject which was clicked/modified.

**Comment by hendrysadrak** [comment]
Hey! If you don't have time yourself i could do it but could you give some guidelines where to start?

**Comment by bfanger** [comment]
I'd rather not expose events to the page, but changes made by the inspector should be made visible.
I was thinking about waiting 1 or 2 animation frames, and if the pixi render method wasn't called, then call the render from the inspector.
