### ISSUE TITLE
Need support for Electron

### ISSUE THREAD

**Issue by soimy** [bfanger/pixi-inspector#20]
Just managed to load PixiJS devtools inside Electron via https://xwartz.gitbooks.io/electron-gitbook/content/en/tutorial/devtools-extension.html
Panel shows but only Reconnect button appeared.
<img width="864" alt="qq20180112-170532 2x" src="https://user-images.githubusercontent.com/1550237/34867394-ee5aa412-f7ba-11e7-8714-965a4187af11.png">

**Comment by bfanger** [comment]
Electron is not a supported platform.
But feel free to implement electron support and create a PR

**Comment by blurymind** [comment]
Has this been implemented yet? I kind of want to add it to gdevelop's electron app, but am getting only the reconnect button like the screenshot

**Comment by djmisterjon** [comment]
inject "chromium-args": "--load extension='./plugins/pixi_devtools_0.9.3_0'",
and just copy past the build somewhere in your projet . example inside plugins folder.
And expose PIXI as global for dev mode
Work fine with `nwjs` on my side, `electron` should also work.
https://github.com/bfanger/pixi-inspector/issues/49
