### ISSUE TITLE
The selected node is not available

### ISSUE THREAD

**Issue by Patrick-Hammond** [bfanger/pixi-inspector#22]
Very useful tool, although I've been getting an error recently, when selecting a node and typing $pixi in the console I get:
**_Uncaught ReferenceError: $pixi is not defined
    at <anonymous>:1:1_**
I'm using Pixi 4.6.2 and it is hosted in an iFrame.

**Comment by csomakk** [comment]
if its within an iframe, you have to select that iframe in chrome from the dropdown, as console targets frames, not global. works for me within iframes.

**Comment by csomakk** [comment]
(its between clear and filter)

**Comment by Patrick-Hammond** [comment]
Hey great! Thanks for that!
I wasn't aware of that console-context dropdown, good to know!
