### ISSUE TITLE
Outliner doesn't take into account canvas scale

### ISSUE THREAD

**Issue by zfmarkham** [bfanger/pixi-inspector#26]
Latest update is drawing outliner without taking into account div scaling.

![pixi debug](https://user-images.githubusercontent.com/13186178/38927783-bdc5b49c-42fe-11e8-912c-276c71c0651a.jpg)

In this example the canvas has a width and height of 1920x1080, but the div it's inside has dimensions of around 1644, 924.

**Comment by csomakk** [comment]
hah, nice one, did that work before? Can you post an example, so I can test a fix?

**Comment by DigitalClouds** [comment]
Here's an example of the issue:

https://codepen.io/Digital-Clouds/pen/KRKQzz

**Comment by csomakk** [comment]
thanks for the example, really helpful :) I had a look, seems like issue was there already. @bfanger probably understands the renderer logic more. At this point to me it seems like we're expecting canvas to be full screen at all times. in InspectorGui.js we calculate some offset, I'd probably fiddle a check in there. but I hope Bob has a better solution :)

**Comment by crossRT** [comment]
Hi there,
I having this issue also. The blue box indicator is not accurate after latest update.

**Comment by themoonrat** [comment]
I understand the reasoning for trying it, but I'm not sure that the latest versions that use a separate canvas to draw the outlines is the way to go. It relies on assumptions on how the page and pixi canvas is setup that is ripe for inaccuracies. A graphic drawn directly onto the actual canvas, and you can't go wrong. I modified my own version to go back to this setup! I gave that graphic a unique name and told the tree listing to ignore that element :)

**Comment by bfanger** [comment]
It allows the abilly to see, where offcanvas sprites are.
I just have to figure out the correct translation between source and the overlay canvas.
I fixed a bug for when the source and overlay use a different resolution , but that fix broke the resized canvas alignment.

**Comment by zfmarkham** [comment]
@themoonrat Out of interest what changes did you make? I want to do the same

**Comment by themoonrat** [comment]
Sure @zfmarkham 

The main changes are...
Remove `services/InspectorGui` - this is the extra canvas. Remove any references to it anywhere
`InspectorHighlight.js` - I create my own graphics box, attach it to the actual canvas, and give it a name property so I can track it elsewhere. The whole file becomes
```
export default class InspectorHighlight {
  constructor(inspector) {
    inspector.registerHook("afterRender", this.update.bind(this));
  }

  update(_, renderer) {
    const stage = renderer._lastObjectRendered;

    if (!this.graphics) {
      if (!window.PIXI) {
        return;
      }
      this.graphics = new window.PIXI.Graphics();
      this.graphics.name = 'pixi-inspector';
      stage.addChild(this.graphics);
    }

    const box = this.graphics;
    const node = InspectorHighlight.node;
    if (node && node.parent) {
      box.visible = true;
      box.clear();
      box.beginFill(0x007eff, 0.3);
      const bounds = node.getBounds();
      stage.worldTransform.applyInverse( bounds, bounds );
      box.drawRect(
        bounds.x,
        bounds.y,
        bounds.width,
        bounds.height
      );
      box.endFill();
    } else {
      box.visible = false;
    }
  }
}

InspectorHighlight.node = false;
```

Finally, in `TreeView.vui` - in 'flattenNode' I add
```
if (node.name === 'pixi-inspector') {
  return;
}
```
just above the `title = node.type + " [" + node.name + "]";` line. ie. won't show this graphics box as being children of any objects in the display tree, even tho technically it now is a child of them.

**Comment by zfmarkham** [comment]
Thanks @themoonrat that's perfect!

**Comment by JulioC** [comment]
I was able to fix this by changing the code from InspectorHighlight.js:
```
      const scale = {
        x: 1 / renderer.resolution, // was this.gui.resolution.x / renderer.resolution
        y: 1/ renderer.resolution //  was this.gui.resolution.y / renderer.resolution
      };
```

@bfanger what's the reason why the gui resolution was being taken in account there?

**Comment by JulioC** [comment]
Indeed. I believe it worked in my case because the game fills the entire window.
I'll investigate it some more

**Comment by zfmarkham** [comment]
I've resolved this locally by using this calculation for the scale:

```
      const canvas = renderer.view;
      const scale = {
        x: canvas.clientWidth / canvas.width,
        y: canvas.clientHeight / canvas.height
      };
```

This works for my situation (the one in the codepen provided), but unsure if it's a solution that will work across everything.
