### ISSUE TITLE
Always crash

### ISSUE THREAD

**Issue by AaronRZH** [bfanger/pixi-inspector#28]
Every time open the inspector page, it runs a while and then crash with the error out-of-menory.

**Comment by csomakk** [comment]
can you elaborate on this please? I've been using it for years without a problem. Whats your setup? Does it happen in incognito? in other machine? do you have conflicting plugins? is it on your own site, or is it on pixi.js homepage too?

**Comment by AaronRZH** [comment]
It happens on a lottery site. Every time I open plugin tab on that site, the plugin will run and display pixi component. But after a while it will crash. You can test it on http://777.koxybp.com/ipl/portal.php/game/lobby_entrance?GameKind=3
