### ISSUE TITLE
editable properties

### ISSUE THREAD

**Issue by csomakk** [bfanger/pixi-inspector#3]
high priority for future ;)

**Comment by csomakk** [comment]
fixed in https://github.com/csomakk/pixi-inspector

**Comment by csomakk** [comment]
I'll make a pull request tomorrow

**Comment by bfanger** [comment]
Used `contentEditable={true}` instead of an `<input>` making the properties editable really makes the inspector more "real". Many thanks for the reference implementation.

**Comment by csomakk** [comment]
:+1: awesome :) when will you release the plugin with the updates to chrome store? :)

**Comment by bfanger** [comment]
Uploaded v0.3 to the chrome webstore. (also includes the names patch)
