### ISSUE TITLE
Trouble with webpack build

### ISSUE THREAD

**Issue by Creta5164** [bfanger/pixi-inspector#34]
![image](https://user-images.githubusercontent.com/13521406/53244514-771cc000-36ee-11e9-9948-153c44e1e2fb.png)

Plugin can't detect Phaser (based on Pixijs) bundled from webpack.
how can I inspect with this?

**Comment by csomakk** [comment]
works for me on https://phaser.io/examples/v2/animation/animation-events
can you try that one please?

**Comment by Creta5164** [comment]
Yeah sure that is works, but, I mean if Pixi(or Phaser) library bundled by webpack, debugger can't detect it.
https://webpack.js.org/

**Comment by Creta5164** [comment]
Here's my webpack config file.

```js
const path = require('path');

module.exports = {
    context: path.resolve(__dirname, 'wwwroot', 'Core'),
    entry: path.join(__dirname, 'wwwroot', 'Core', '/Main.ts'),
    output: {
        filename: 'game-core.js',
        path: path.join(__dirname, 'wwwroot', 'js')
    },
    module: {
        rules: [
            {
                test: /\.tsx?$/,
                loader: 'ts-loader',
                exclude: /node_modules/,
            },
            { test: /\.js$/, loader: 'source-map-loader', enforce: 'pre' }
        ]
    },
    resolve: {
        extensions: [".tsx", ".ts", ".js"]
    },
    devtool: 'eval-source-map'
};
```

And this is entry point
```ts
import * as Phaser from 'phaser';

export class GameManager
{
    /** RootUrl for resources of game. */
    private static RootUrl: string;
    
    /** Current Phaser program. */
    private static Application: Phaser.Game;
    
    public static Init(url :string) :void
    {
        this.SetupUrl(url);
        
        if (this.Application != null) {
            this.Application.destroy(true);
            this.Application = null;
        }
        
        this.Application = new Phaser.Game({
            type: Phaser.AUTO,
            width: 800,
            height: 600,
            
            physics: {
                default: 'arcade'
            },
            
            scene: {
                preload: this.OnPreload,
                create:  this.OnApplicationReady
            }
            
        });
    }
...
```

**Comment by csomakk** [comment]
if you can share a sample minimal project with your webpack setup, etc, on the weekend i might have a few mins to look into it. My guess that the detection runs only once there..

**Comment by Creta5164** [comment]
Repository : https://github.com/Project-Seiklus/SeiklusRPG-Editor/tree/core-function

1. open `Core` folder using vscode
2. <kbd>Ctrl</kbd> + <kbd>\`</kbd> to open terminal with current path.
3. run `npm install`
4. Open `index.html` in `wwwroot` folder.
5. (External) Install .NET Core SDK 2.0 or higher and launch debug mode in vscode (automatically setup)
![image](https://user-images.githubusercontent.com/13521406/53245595-7afe1180-36f1-11e9-81fc-3d3c67a04a4d.png)

**Comment by Creta5164** [comment]
Sorry for several time edited this...

**Comment by TombolaShepless** [comment]
Also having this exact issue

**Comment by bfanger** [comment]
You'll need to manually register the PIXI variable to the pixi inspector.

```js
window.__PIXI_INSPECTOR_GLOBAL_HOOK__ &&  window.__PIXI_INSPECTOR_GLOBAL_HOOK__.register({ PIXI: window.PIXI });
```
https://github.com/bfanger/pixi-inspector/blob/master/tests/example.js#L7-L8

**Comment by Creta5164** [comment]
![image](https://user-images.githubusercontent.com/13521406/53296105-11464a80-384c-11e9-9b1c-b22dca5098b5.png)

```js
__PIXI_INSPECTOR_GLOBAL_HOOK__.register({ PIXI: window.Phaser });
```
It looks like detected it, but it does not seem to find the application.

**Comment by bfanger** [comment]
You're passing Phaser, not PIXI. Phaser used to have Phaser.PIXI. if you also pass Phaser to the register method it'll show the phaser icon and version

**Comment by Creta5164** [comment]
![image](https://user-images.githubusercontent.com/13521406/53298624-f8518f80-3873-11e9-85e8-76f94146fb69.png)
```js
__PIXI_INSPECTOR_GLOBAL_HOOK__.register({ PIXI: window.Phaser.PIXI });
```
There's doesn't exist PIXI :|

**Comment by themoonrat** [comment]
Phaser 3 no longer uses PixiJS as its renderer

**Comment by Creta5164** [comment]
http://www.html5gamedevs.com/topic/34261-does-phaser-3-use-pixijs/

I just found this thread... okay so close this issue.
