### ISSUE TITLE
debug app on remote device

### ISSUE THREAD

**Issue by MatsMaker** [bfanger/pixi-inspector#36]
I'm able to debug without problems on chrome but i'm not able to debug app on remote device
Pixi window is always empty

![Schermata 2019-05-24 alle 12 25 00](https://user-images.githubusercontent.com/253032/58321662-0d13d400-7e1f-11e9-9446-caf597e8461b.png)

_Originally posted by @xyzdevelopment in https://github.com/bfanger/pixi-inspector/issues/35#issuecomment-495563001_

**Comment by MatsMaker** [comment]
@xyzdevelopment
I think it isn't possible to fix. Because of the remote chrome app doesn't have this extension. :(
Of course, maybe some else will fix it

If you will be interesting you can try using [this app  ](https://github.com/MatsMaker/pixijs-remote-helper) now.

**Comment by bfanger** [comment]
@MatsMaker Nice work!

Closing the issue, looks like this is something only the chrome team could fix.
