### ISSUE TITLE
chrome extension 0.9.0 with pixi.js 4.6.2 doesn't work on windows

### ISSUE THREAD

**Issue by ridakk** [bfanger/pixi-inspector#40]
once the version pixi-inspector version is upgraded to v0.9.0. extension stopped working. i build v0.8.0 as a workaround.

pixi.js: 4.6.2

**Comment by bfanger** [comment]
Thanks, seems the changes for improving v5 support broke v4.

**Comment by iamjojo1225** [comment]
Will the version of 0.8.0 be downloaded?
How do I downgrade the version?

**Comment by bfanger** [comment]
Fixed in 0.9.1
