### ISSUE TITLE
Pixi Inspector is showing empty for Pixi V4 version

### ISSUE THREAD

**Issue by sksshareef** [bfanger/pixi-inspector#41]
Pixi Inspector is showing empty for Pixi V4 version

**Comment by rlthomasgames** [comment]
seeing the same, but only for localhost

**Comment by bfanger** [comment]
Which version are you using? 
0.9.0 had a bug, which should be fixed with 0.9.1

**Comment by sksshareef** [comment]
I have install the Inspector from chrome : PixiJS devtools 0.9.1, It was not working at localhost but now its working. What was the issue ?

**Comment by bfanger** [comment]
To prevent a deprecation warning in v5 for PIXI.WebGLRenderer i needed to check if the new PIXI.Renderer existed, but I made mistake in the check.

**Comment by rlthomasgames** [comment]
yeah seems all good again now, thanks!
