### ISSUE TITLE
It does not work in webpack

### ISSUE THREAD

**Issue by hufei1993** [bfanger/pixi-inspector#42]
It does not work in webpack

**Comment by csomakk** [comment]
Yes it does, see closed issues.

**Comment by csomakk** [comment]
webpack.config.js

for typescript:
plugins: [
//...
    new webpack.ProvidePlugin({
      PIXI: 'pixi.js'
    })
  ]

for creating app:
import * as PIXI from 'pixi.js';

export class PixiAppManager {

    app:PIXI.Application;

    public createApp() {
        this.app = new PIXI.Application({ width: 800, height: 600, backgroundColor: 0x1099bb });
        document.body.appendChild(this.app.view);
        this.registerPixiInspector();
    }

    registerPixiInspector() {
        (window as any).__PIXI_INSPECTOR_GLOBAL_HOOK__ &&  (window as any).__PIXI_INSPECTOR_GLOBAL_HOOK__.register({ PIXI: PIXI });
    }
}

**Comment by MatsMaker** [comment]
> It does not work in webpack

Example:

https://github.com/MatsMaker/example-of-migration-pixijs-imspector-to-5v/tree/gh-pages

**Comment by csomakk** [comment]
if this haven't resolved issue for you, see https://github.com/bfanger/pixi-inspector/issues/34
