### ISSUE TITLE
Duplicating properties and devtool stucking

### ISSUE THREAD

**Issue by estashuk** [bfanger/pixi-inspector#44]
Pixi devtool duplicates some properties of component and got stuck until "reconnect" is pressed. I got issue with duplicating properties in last commit and no devtool stucking.

**Comment by estashuk** [comment]
![image](https://user-images.githubusercontent.com/25328829/72720376-769cdb80-3b82-11ea-848f-107de0628392.png)

**Comment by MatsMaker** [comment]
> Pixi devtool duplicates some properties of component and got stuck until "reconnect" is pressed. I got issue with duplicating properties in last commit and no devtool stucking.

**Comment by MatsMaker** [comment]
Hi,
I found this row doing duplicate props. And created new [PR](https://github.com/bfanger/pixi-inspector/pull/45).
Bob, please see what for need removed rows

**Comment by estashuk** [comment]
After some research, pixi inspector got stucked because of error
