### ISSUE TITLE
properties

### ISSUE THREAD

**Issue by genesis-esther** [bfanger/pixi-inspector#47]
because of this fix merged 3 days ago

> FIX: remove duplicate props #45

most pixi's value won't show anymore ( transform.pivot, transform.position, transform.scale... )
<img width="267" alt="oao" src="https://user-images.githubusercontent.com/29696898/81260603-eae58700-906c-11ea-8ca5-f3506368e3a1.png">

**Comment by rapt0p7** [comment]
➕
It's making extensions unuseful.

**Comment by MatsMaker** [comment]
> because of this fix merged 3 days ago
> 
> > FIX: remove duplicate props #45
> 
> most pixi's value won't show anymore ( transform.pivot, transform.position, transform.scale... )
> <img alt="oao" width="267" src="https://user-images.githubusercontent.com/29696898/81260603-eae58700-906c-11ea-8ca5-f3506368e3a1.png">

Are you use pixi.js v4?

**Comment by bfanger** [comment]
Fixed it in 0.9.3
