### ISSUE TITLE
DOMException: Failed to execute 'postMessage' on 'Window': function () { [native code] } could not be cloned

### ISSUE THREAD

**Issue by MercurialUroboros** [bfanger/pixi-inspector#53]
![image](https://user-images.githubusercontent.com/22802482/89117402-cf3c2200-d49d-11ea-8728-a4dba3f793d7.png)

Hi, has anyone ever encountered this issue? My Pixi application works just fine, but the Pixi devtool refuses to work

Step to reproduce:
Just click on the Pixi devtools.

**Comment by csomakk** [comment]
If you handle post messages between iframes you need to check them safely
first, so it won't cause this runtime exception. Otherwise I'd debug your
code ;)

**Comment by MercurialUroboros** [comment]
It was not the case, it was actually one of my components creating this conflict. Thanks anyway
