### ISSUE TITLE
Other browsers ?

### ISSUE THREAD

**Issue by adamprocter** [bfanger/pixi-inspector#55]
Is there a way to inspect within Firefox or Safari on macOS and not Chrome ? I have a number of dynamic buttons and I want confirm each one has its own unique name attribute but I cant tell and really don't want to have to install Chrome

**Comment by bfanger** [comment]
No, this project is build as a chrome extension.

I believe the extension api's are similar,  you could try to port the extension. Let us know if you've got it working in firefox

**Comment by adamprocter** [comment]
Ok I did try but the tab for PIXI never shows.. I tried the added  in console window.PIXI = PIXI and get

VM1774:1 Uncaught ReferenceError: PIXI is not defined
    at <anonymous>:1:15
(anonymous) @ VM1774:1
