### ISSUE TITLE
Cannot detect PIXI elements

### ISSUE THREAD

**Issue by ozdenakca** [bfanger/pixi-inspector#59]
The inspector cannot detect any PIXI elements. I use typescript with webpack and PIXI 5.2.0.

**Comment by csomakk** [comment]
see https://github.com/bfanger/pixi-inspector/issues/42 
works like a charm with PIXI 5.3.3 and webpack
<img width="559" alt="Screenshot 2020-12-30 at 14 46 20" src="https://user-images.githubusercontent.com/629462/103355128-ca5fb680-4aad-11eb-9bfe-a4c64d980663.png">

**Comment by ozdenakca** [comment]
I already tried every suggestion on every other issue. Nothing worked up until now.

**Comment by csomakk** [comment]
ok, then help us please. same setup works for us. (pixi minor won't make difference) 
ideas: 
You'll need to manually register the PIXI variable to the pixi inspector.

window.__PIXI_INSPECTOR_GLOBAL_HOOK__ &&  window.__PIXI_INSPECTOR_GLOBAL_HOOK__.register({ PIXI: window.PIXI });

also check if all is there.

**Comment by ozdenakca** [comment]
I have also added this but like this:
(window as any).PIXI_INSPECTOR_GLOBAL_HOOK && (window as any).PIXI_INSPECTOR_GLOBAL_HOOK.register({ PIXI: window.PIXI });
but didnt work anyway.

**Comment by csomakk** [comment]
also can try like this.
        window.__PIXI_INSPECTOR_GLOBAL_HOOK__ && window.__PIXI_INSPECTOR_GLOBAL_HOOK__.register({ PIXI });

**Comment by optama** [comment]
This line worked for me `window.__PIXI_INSPECTOR_GLOBAL_HOOK__ && window.__PIXI_INSPECTOR_GLOBAL_HOOK__.register({ PIXI: PIXI });` as per the sample in #42
