### ISSUE TITLE
Pixi v6 support

### ISSUE THREAD

**Issue by SerG-Y** [bfanger/pixi-inspector#74]
Hey! Is it possible to run `pixi-inspector` without global PIXI using pixi v6 with individual package imports? 
Maybe it's possible to create pseudo PIXI and inject it through `__PIXI_INSPECTOR_GLOBAL_HOOK__.register`?

**Comment by bfanger** [comment]
Yes (make sure to check if __PIXI_INSPECTOR_GLOBAL_HOOK__ exists before calling register)

**Comment by SerG-Y** [comment]
@bfanger can you please list what should be in pseudo PIXI object Renderer, Container, stage something else? Thanks!

**Comment by bfanger** [comment]
I cant provide a list, supporting the different PIXI versions is hard enough, feel free to share what worked for you, that will help others. Tip: pass a [proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) that will allow you to log which properties are accessed

**Comment by hlobka** [comment]
Not sure that I can solve this issue. Proxy is only listening to the version of the PIXI object, what else do we need to add to it?
