### ISSUE TITLE
Unchecked runtime.lastError: The message port closed before a response was received

### ISSUE THREAD

**Issue by kolombet** [bfanger/pixi-inspector#76]
This extension is spamming console with the messages: 
`Unchecked runtime.lastError: The message port closed before a response was received.`

I found similar issues caused by chrome changes to cross-origin requests
https://support.google.com/chrome/thread/2047906/unchecked-runtime-lasterror-the-message-port-closed-before-a-response-was-received?msgid=2556826

This issue reproduced for any pixi content in modern browsers.

**Comment by bfanger** [comment]
I'm using Chrome 94 on macOS and don't see the error you're describing, can you provide details?
