### ISSUE TITLE
filters props

### ISSUE THREAD

**Issue by djmisterjon** [bfanger/pixi-inspector#82]
hi, it will be awesome to also have a properties filter, if you can and have time.:) 
example if i want compare and check between multiple instance those entries separate by comma `[group,alpha,isMask]`.

![image](https://user-images.githubusercontent.com/24865815/163169517-ea477d67-5c7f-48c3-a12a-74b448975d65.png)

**Comment by jeth88** [comment]
Hi,

Your layout seems a little different to mine. Is that an old layout of the plugin?

Thanks.

**Comment by djmisterjon** [comment]
> Hi,
> 
> Your layout seems a little different to mine. Is that an old layout of the plugin?
> 
> Thanks.


yes it old
