### ISSUE TITLE
Add dark theme.

### ISSUE THREAD

**Issue by Ayfri** [bfanger/pixi-inspector#83]
Hi, I'm using Brave and I don't know if it is normal but when I open the PIXI devtools, they are in a white theme which is difficult to read.
![image](https://user-images.githubusercontent.com/34159136/164788532-b7799760-c7ae-46fa-8375-b90029a229d9.png)
It would be very great to have a dark theme matching the Chrome devtools theme.

**Comment by bfanger** [comment]
Looks like chrome changed the default css for chrome extensions, which broke our darkmode. 
Thanks for reporting.

**Comment by djmisterjon** [comment]
this do the job on my side 
![image](https://user-images.githubusercontent.com/24865815/166941252-0d493ab6-1217-42ad-be38-4a4fcb08ccbc.png)

**Comment by MuTsunTsai** [comment]
@djmisterjon Could you make a PR then? I would love to see this issue fixed.

**Comment by bfanger** [comment]
Should be fixed in the 0.9.6 update

**Comment by djmisterjon** [comment]
closing https://github.com/bfanger/pixi-inspector/pull/86
![image](https://user-images.githubusercontent.com/24865815/169601682-f99a7f59-4b32-4252-9f00-64af9f9bf9f9.png)
autor make a fix

**Comment by Ayfri** [comment]
Neat !
