### ISSUE TITLE
is pixi  v6 supported?

### ISSUE THREAD

**Issue by bcq028** [bfanger/pixi-inspector#88]
it seems not working.
I use vite to create empty nodejs project and try to register PIXI, but failed. I don't know the exact reason, pixi version,chrome version, or vite?
![image](https://user-images.githubusercontent.com/108849949/198250511-ec384adc-4450-4f4d-8478-edc90895afc3.png)

Chrome version:Version 106.0.5249.119
Pixi version: 6.5.6

**Comment by bfanger** [comment]
Yes, pixi.js 6  (and 7) are supported. Also when using ⚡️Vite.

Example:

```js
import * as PIXI from "pixi.js"

window.PIXI = PIXI; // <-- This line allows the inspector to inject it hooks

const app = new  PIXI.Application({width: 800, height: 600})
document.body.appendChild(app.view)
const bunny = PIXI.Sprite.from("https://pixijs.io/examples/examples/assets/bunny.png")
app.stage.addChild(bunny)
```
