### ISSUE TITLE
Is there any plan to support pixi.js@7.x version ?

### ISSUE THREAD

**Issue by vincentSea** [bfanger/pixi-inspector#90]
Hi, Is there any plan to support pixi.js@7.x version ?

**Comment by bfanger** [comment]
It already does, but you are probably using webpack or vite. Which needs additional steps to expose the PIXI object to the extension

**Comment by brunocapdevila** [comment]
Also using Vite and Pixi 7.x. 
Adding `window.PIXI = PIXI;` to my code makes the tab appear, but then I get this

`
pixi.inspector.bundle.js:2 Uncaught TypeError: Function has non-object prototype 'undefined' in instanceof check
    at [Symbol.hasInstance] (<anonymous>)
    at Y.resolveType (pixi.inspector.bundle.js:2:19804)
    at Y.detectType (pixi.inspector.bundle.js:2:19664)
    at Ht.serialize (pixi.inspector.bundle.js:2:42431)
    at pixi.inspector.bundle.js:2:42788
    at Array.map (<anonymous>)
    at Ht.serialize (pixi.inspector.bundle.js:2:42775)
    at Ht.detectScene (pixi.inspector.bundle.js:2:41720)
    at $t (pixi.inspector.bundle.js:2:43291)
    at e.render (pixi.inspector.bundle.js:2:44701)
`

**Comment by krimeshu** [comment]
> Also using Vite and Pixi 7.x. Adding `window.PIXI = PIXI;` to my code makes the tab appear, but then I get this error when opening it
> 
> ```
> pixi.inspector.bundle.js:2 Uncaught TypeError: Function has non-object prototype 'undefined' in instanceof check
>     at [Symbol.hasInstance] (<anonymous>)
>     at Y.resolveType (pixi.inspector.bundle.js:2:19804)
>     at Y.detectType (pixi.inspector.bundle.js:2:19664)
>     at Ht.serialize (pixi.inspector.bundle.js:2:42431)
>     at pixi.inspector.bundle.js:2:42788
>     at Array.map (<anonymous>)
>     at Ht.serialize (pixi.inspector.bundle.js:2:42775)
>     at Ht.detectScene (pixi.inspector.bundle.js:2:41720)
>     at $t (pixi.inspector.bundle.js:2:43291)
>     at e.render (pixi.inspector.bundle.js:2:44701)
> ```

Same to me, it seems will happen when i create child class by extend Sprite or any other pixi class.

**Comment by prinsss** [comment]
Same problem here with pixi.js v7 + vite. It seems that pixi-inspector will search for types on given `PIXI` object, and error occurs when there is any custom pixi element in scene graph (which does not exists on `window.PIXI`).

Since the `PIXI` imported is sealed object and we cannot modify it directly, I tried to pass a `Proxy` object to pixi-inspector and it works fine with custom DisplayObjects. :)

```js
import * as PIXI from 'pixi.js';

const PIXI_EXTRA = {
    'MyCustomElement': MyCustomElement, // which extends PIXI.DisplayObject
}

window.PIXI = new Proxy({}, {
    get(target, p) {
        // See: https://github.com/bfanger/pixi-inspector/blob/master/src/services/Inspector.js#L28
        if (p in PIXI) return PIXI[p];
        if (p in PIXI_EXTRA) return PIXI_EXTRA[p];
        return undefined;
    },
    has(target, p) {
        return Reflect.has(PIXI, p) || Reflect.has(PIXI_EXTRA, p);
    },
    ownKeys() {
        return [...Reflect.ownKeys(PIXI), ...Reflect.ownKeys(PIXI_EXTRA)];
    },
    getOwnPropertyDescriptor(target, p) {
        const result = Reflect.getOwnPropertyDescriptor(PIXI, p)
            || Reflect.getOwnPropertyDescriptor(PIXI_EXTRA, p);

        if (!result) return undefined;
        return {
            ...result,
            configurable: true,
        };
    },
});
```

**Comment by MuTsunTsai** [comment]
I'm having the same issue and the cause is also because I have custom `DisplayObject` subclasses, and the workaround mentioned above works. Hoping to see the inspector have better support for custom objects.

**Comment by lykl** [comment]
Is there any progress?
