### ISSUE TITLE
Redundant root nodes in outliner

### ISSUE THREAD

**Issue by MuTsunTsai** [bfanger/pixi-inspector#92]
As far as I can tell from this part of the source code https://github.com/bfanger/pixi-inspector/blob/2210ae0689df58aebbb6827591a68c6859e544f4/src/services/InspectorOutliner.js#L140-L152

Whenever a container is rendered for the first time, the inspector adds it as a new root node, and never removes it. This could lead to redundant root nodes if

1. The container is later destroyed, or
2. The container is actually in other parts of the tree already (or is added to other parts of the tree later), and it's rendered separately only for special reasons (e.g. by setting its `cacheAsBitmap` to `true`)

I suggest that there should be a better mechanism for checking these two cases and remove such nodes from the root.

**Comment by bfanger** [comment]
Fixed in 2.0.0 as the root is now based on the `PIXI.Application.stage`.
