### ISSUE TITLE
Not all properties is shown in the properties panel

### ISSUE THREAD

**Issue by AndreiMrakov** [bfanger/pixi-inspector#94]
There is no way to show ALL the properties of the pixi component like "**...**" or "**show all**", only 1 way to "**Log to console**" and set object as global variable(not very handy). Also will be great if nested objects become expandable 
_PS: It's unreal even to check the components size or sprite source(sizes is very useful)_

PixiJS: 5.2.1
Environment: MacOS Venture 13.1
Browser: Microsoft Edge Version 108.0.1462.54

![pixijs-extension-properties-issue](https://user-images.githubusercontent.com/21972136/209979749-7b14e5c9-f3e6-4597-921f-dc7eeb02d54c.png)

**Comment by bfanger** [comment]
Closing as 2.0 uses a different design approach. 
We hope to add more info panels in the future.

For now the way to explore properties is the `$pixi` in the developer console.
