### ISSUE TITLE
 Problems using PIXI.Application

### ISSUE THREAD

**Issue by roman-kripton** [bfanger/pixi-inspector#98]
Hello, I've run into this problem. What if I don't use PIXI.Application ?
![image](https://user-images.githubusercontent.com/69865177/223030574-8dea1476-059f-42fb-869a-373ec2289b7b.png)

**Comment by bfanger** [comment]
Set __PIXI_APP__ to an object that looks like an PIXI.Application 


May I ask why you dont use an Application?

**Comment by Outfire** [comment]
Hi. Thank you for the great extension. 
I also don't use an Application. Because we have our structure for rendering object. All what I can is provide root container for rendering.
Do you need only stage from an Application or any other additional infoarmation and methods?

**Comment by MaksimPozharskiy** [comment]
I did as advised @Outfire , instead of app I put stage and devtools started working.

But the items are not showing.
P.S. I'm not using the latest version of Pixi , i use v2.2.9
![image](https://user-images.githubusercontent.com/47855527/223063889-1d8d641b-743d-427f-8ce7-d407248cc620.png)

**Comment by Tezza48** [comment]
This is also an issue for me, It's pretty common that PIXI apps don't use Application. As per the docs it's only a convenience class.

https://pixijs.download/release/docs/PIXI.Application.html

It boots up some stuff that we just don't need or have alternatives for.

Something quick and helpful would be pulling out your required fields from Application instead and a suggestion in `Instructions.svelte`.

Something like
```ts
globalThis.__PIXI_APP__ = {
    stage: ...,
    renderer: ...,
    ...
}
```

**Comment by goldenratio** [comment]
Hey,
Thanks for the update and moving Svelte :D nice stuff.
is it worth checking for `window.PIXI` to be backwards compatible?
https://github.com/bfanger/pixi-inspector/blob/v0.9.6/src/services/DevConnection.js#L12

**Comment by gatsinski** [comment]
I've tested 5459a57e6b90f510499398683761059071b52642 locally and it works like a charm. Thanks, @bfanger for the quick response.

**Comment by bfanger** [comment]
2.1.0 is submitted to the chrome store
